data_params:
  raw_data_path: "data/raw/data.csv"
  n_samples: 200
  n_features: 30
  test_size: 0.3
  train_data_path: "data/processed/train.csv"
  test_data_path: "data/processed/test.csv"
train_params:
  n_estimators: 100
  model_path: "models/model.pkl"
  metrics_path: "reports/metrics.json"
random_state: 17
