sql_params:
  username: mlflow
  password: password
  database: postgres
  ip: localhost
data_params:
  raw_data_path: "data/raw/data.csv"
  n_samples: 100
  n_features: 4
  test_size: 0.2
  train_data_path: "data/processed/train.csv"
  test_data_path: "data/processed/test.csv"
  train_sql_tablename: "train_data"
  test_sql_tablename: "test_data"
train_params:
  n_estimators: 10
  model_path: "models/model.pkl"
  metrics_path: "reports/metrics.json"
random_state: 17
