apiVersion: v1 
kind: Pod
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: l3lush/online_inference:v1
      name: fastapi-ml
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "10Gi"
          cpu: "1000m"
