apiVersion: v1 
kind: Pod
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: l3lush/online_inference:v2
      name: fastapi-ml
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /ready
          port: 80 
        initialDelaySeconds: 15
        periodSeconds: 3
